export const projects = [
  {
    id: 1,
    title: "",
    date: "J",
    description: "",
    image: "",
    tags: [],
    category: "html-css",
    github: "",
    webapp: "",
  },
  {
    id: 2,
    title: "",
    date: "",
    description: "",
    image: "",
    tags: [],
    category: "html-css",
    github: "",
    webapp: "",
  },
  {
    id: 3,
    title: "",
    date: "",
    description: "",
    image: "",
    tags: [""],
    category: "html-css",
    github: "",
    webapp: "",
  },
  {
    id: 4,
    title: "",
    date: "",
    description: "",
    image: "",
    tags: [],
    category: "html-css",
    github: "",
    webapp: "",
  },
  {
    id: 5,
    title: "",
    date: "",
    description: "",
    image: "",
    tags: [""],
    category: "react",
    github: "",
    webapp: "",
  },
  {
    id: 6,
    title: "",
    date: "",
    description: "",
    image: "",
    tags: [""],
    category: "full-stack",
    github: "",
    webapp: "",
  },
  {
    id: 7,
    title: "",
    date: "",
    description: "",
    image: "",
    tags: [""],
    category: "javascript",
    github: "",
    webapp: "",
  },
  {
    id: 8,
    title: "",
    date: "",
    description: "",
    image: "",
    tags: [""],
    category: "html-css",
    github: "",
    webapp: "",
  },
  {
    id: 9,
    title: "",
    date: "",
    description: "",
    image: "",
    tags: [""],
    category: "html-css",
    github: "",
    webapp: "",
  },
  {
    id: 10,
    title: "",
    date: "",
    description: "",
    image: "",
    tags: [""],
    category: "html-css",
    github: "",
    webapp: "",
  },
  {
    id: 11,
    title: "",
    date: "",
    description: "",
    image: "",
    tags: [""],
    category: "javascript",
    github: "",
    webapp: "",
  },
  {
    id: 12,
    title: "",
    date: "",
    description: "",
    image: "",
    tags: [""],
    category: "react",
    github: "",
    webapp: "",
  },
];
